/*
 * Copyright 2013 Jive Software
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/**
 * Library for manipulating external stream instances.
 */

var q = require('q');
var util = require('util');
var instances = require('./instances');
var pusher = require('./dataPusher');
var jive = require('../api');

var extstreams = Object.create(instances);
module.exports = extstreams;

extstreams.getCollection = function() {
    return "extstreamInstance";
};

extstreams.pushActivity = function ( tileInstance, activity) {
    return pusher.pushActivity(tileInstance, activity);
};

var pushComment = function ( tileInstance, comment, commentURL) {
    return pusher.pushComment(tileInstance, commentURL, comment);
};

/**
 * Create a comment in Jive on an activity that was generated by an external stream.
 *
 * @param activity - activity object returned from jive. For example, an object returned in the promise by extstreams.pushActivity method
 * @param comment - comment JSON, see https://developers.jivesoftware.com/api/rest/CommentEntity.html
 *
 * @returns a promise that resolves with a response object. response.entity is the created comment that is returned from Jive
 */
extstreams.commentOnActivity = function(activity, comment ) {
    if (!(activity && activity.resources && activity.resources.comments && activity.resources.comments.ref)
        || !activity.parent) {

        throw new Error('Error in jive.extstreams.commentOnActivity: input activity is not a valid Jive object.' +
            'It is missing the resources.comments.ref field or parent field.');
    }
    var commentsURL = activity.resources.comments.ref;
    var parentInstanceURL = activity.parent + '/activities';

    return extstreams.findByURL(parentInstanceURL).then(function(extstream) {
        if (!comment.externalID){
            comment.externalID = extstream.name + '_' + 'comment' + '_' + String(new Date().getTime());
            jive.logger.warn(util.format('No externalID field given when creating new comment. Assigning ID %s', comment.externalID ));
        }
        return pushComment(extstream, comment, commentsURL);
    });

};

/**
 * Get all the comments in Jive for a given activity object.
 *
 * @param activity - activity object
 * @param optionalFieldList - an array of strings. The fields from the returned comments to be present
 * @param optionalItemsPerPage - defaults to 25. Number of comments returned per request.
 * @param commentSourceType - string. Must be 'ALL', 'JIVE', or 'EXTERNAL'. If not specified, defaults to 'ALL'
 * @returns a promise that resolves to a response. response.entity is the list of comments. See  See https://developers.jivesoftware.com/api/rest/index.html#lists
 */
extstreams.fetchCommentsOnActivity = function(activity, optionalFieldList, optionalItemsPerPage, commentSourceType) {
    if (!(activity && activity.resources && activity.resources.comments && activity.resources.comments.ref)
        || !activity.parent) {
        throw new Error('Error in jive.extstreams.fetchCommentsOnActivity: ' +
            'input activity is not a valid Jive object. It is missing the resources.comments.ref field or parent field.');
    }

    var commentsURL = activity.resources.comments.ref;

    commentsURL += buildQueryString(optionalFieldList, optionalItemsPerPage, commentSourceType);

    var parentInstanceURL = activity.parent + '/activities';
    return extstreams.findByURL(parentInstanceURL).then( function(extstream) {
        return pusher.getPaginated(extstream, commentsURL );
    }).then(function(response){
            if (200 <= response.statusCode && response.statusCode <= 299) {
                response.entity.list = filterComments(response.entity.list, commentSourceType);
            }
            return response;
        });
};

/**
 * Get all comments in Jive for ALL activity of the given external stream
 * @param extstream - an external stream object from the jive-sdk
 * @param optionalFieldList - an array of strings. The fields from the returned comments to be present
 * @param optionalItemsPerPage -  defaults to 25. Number of comments returned per request.
 * @param commentSourceType - string. Must be 'ALL', 'JIVE', or 'EXTERNAL'. If not specified, defaults to 'ALL'.
 * @returns a promise that resolves to a response. response.entity is the list of comments. See  See https://developers.jivesoftware.com/api/rest/index.html#lists
 */
extstreams.fetchAllCommentsForExtstream = function(extstream, optionalFieldList, optionalItemsPerPage, commentSourceType) {

    var dataURL = extstream['url'];
    var commentsURL = commentsUrlFromDataUrl(dataURL);

    commentsURL += buildQueryString(optionalFieldList, optionalItemsPerPage, commentSourceType);

    return pusher.getPaginated(extstream, commentsURL).then(function(response) {

        if (200 <= response.statusCode && response.statusCode <= 299) {
            response.entity.list = filterComments(response.entity.list, commentSourceType);
        }
        return response;
    });

};

function buildQueryString(optionalFieldList, optionalItemsPerPage, commentSourceType) {
    var queryStr = '';
    if (optionalFieldList || optionalItemsPerPage || (commentSourceType && commentSourceType.toUpperCase() === 'JIVE')) {
        queryStr += '?';

        var q = false;
        if (optionalFieldList) {
            if (optionalFieldList.indexOf('externalID') < 0) { //Must return the externalID to be able to filter properly by comment source
                optionalFieldList.push('externalID');
            }
            queryStr +=  'fields=' + encodeURIComponent(optionalFieldList.join(','));
            q = true;
        }
        if (optionalItemsPerPage) {
            queryStr += (q ? '&' : '') + 'count=' + optionalItemsPerPage;
            q = true;
        }
        if (commentSourceType && commentSourceType.toUpperCase() === 'JIVE') {
            queryStr += (q ? '&' : '') + 'filter=omitExternal'; //For efficiency add filter that omits external comments
            q = true;
        }
    }

    return queryStr;

}

//Sort of a hack to build the comments URL, because we are not storing the "resources" JSON from a Jive external stream object currently
function commentsUrlFromDataUrl(dataURL) {
     return dataURL.slice(0, dataURL.indexOf('activities')) + 'comments';
}

//Helper to filter comments based on whether the externalID field is present
function filterComments(list, commentSourceType) {
    if (!commentSourceType || commentSourceType.toUpperCase() == 'ALL') {
        return list;
    }
    if (commentSourceType.toUpperCase() == 'JIVE') {
        return list.filter(function(comment) {
            return comment.externalID == undefined;
        }) ;
    }
    else if (commentSourceType.toUpperCase() == 'EXTERNAL') {
        return list.filter(function(comment) {
            return comment.externalID != undefined;
        }) ;
    }
    return list;
}